import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const root = new URL("..", import.meta.url);
const read = (path) => readFileSync(new URL(path, root), "utf8");

test("portfolio surface keeps its core experience contracts", () => {
  const experience = ["components/portfolio-experience.tsx", "components/home-project-preview.tsx", "content/projects.ts", "content/credentials.ts", "content/technologies.ts", "components/site-header.tsx", "components/site-preferences.tsx", "components/credential-viewer.tsx"].map(read).join("\n");
  const canvas = read("components/cosmic-canvas.tsx");
  const backdrop = read("components/worldline-backdrop.tsx");
  const styles = read("app/globals.css");
  const layout = read("app/layout.tsx");
  const smoothScroll = read("components/smooth-scroll.tsx");
  const robots = read("app/robots.ts");
  const sitemap = read("app/sitemap.ts");

  assert.match(experience, /I build things I actually see\./);
  assert.match(experience, /Aku membangun hal yang benar-benar kulihat\./);
  assert.match(experience, /certificate-shelf/);
  assert.match(experience, /HomeProjectPreview/);
  assert.match(experience, /featuredOrder !== null/);
  assert.doesNotMatch(experience, /className="academic-card"|className="client-card"|showCertificateArchive|certificate-archive-toggle/);
  assert.match(experience, /credential-dialog/);
  assert.match(experience, /AnimatePresence/);
  assert.match(experience, /gemini-certified-educator\.png/);
  assert.match(experience, /google-student-ambassador\.png/);
  assert.match(experience, /The Henry method/);
  assert.match(experience, /Technology stack orbit/);
  assert.match(experience, /maker-orbit/);
  assert.match(experience, /CarFront/);
  assert.match(experience, /FlaskConical/);
  assert.match(experience, /ShoppingCart/);
  assert.match(experience, /AI-Gesture-Cat/);
  assert.match(experience, /catmoji-hero\.png/);
  assert.match(experience, /polara-og\.png/);
  assert.match(experience, /\["PHP", "php"/);
  assert.match(experience, /tech-icon-fallback/);
  assert.match(experience, /arrival-mark/);
  assert.match(experience, /Skip intro/);
  assert.doesNotMatch(experience, /loader-system/);
  assert.doesNotMatch(experience, /loader-telemetry/);
  assert.doesNotMatch(experience, /hero-transition|The signal is live|aria-label="(?:Previous|Next) project"/);
  assert.doesNotMatch(experience, /className="field-continuum-visual"/);
  assert.match(experience, /worldlineProgress/);
  assert.match(experience, /WorldlineStage/);
  assert.match(experience, /WorldlineBackdrop/);
  assert.doesNotMatch(experience, /signal-constellation/);
  assert.doesNotMatch(experience, /world-chain/);
  assert.match(experience, /project-showcase-index/);
  assert.match(experience, /access: Record<Language, string>/);
  assert.doesNotMatch(experience, /className="chapter-rail"/);
  assert.match(experience, /id="method"/);
  assert.match(experience, /signal-progress/);
  assert.doesNotMatch(experience, /PhaseBridge/);
  assert.match(experience, /--node-color/);
  assert.match(experience, /maker-orbit-inspector/);
  assert.match(experience, /SmoothScroll/);
  assert.match(experience, /data-lenis-prevent/);
  assert.match(experience, /maker-core-portrait/);
  assert.match(experience, /data-active-world=\{activeProject.id\}/);
  assert.doesNotMatch(experience, /method-scene/);
  assert.match(experience, /offset: \["start 85%", "center center"\]/);
  assert.match(experience, /activeMethodStep = motionOn \? methodStep : 2/);
  assert.match(experience, /aria-current=\{index === activeMethodStep \? "step" : undefined\}/);
  assert.match(experience, /ProjectSignature/);
  assert.match(experience, /project signature/);
  assert.match(experience, /stackStageRotate/);
  assert.match(experience, /field-continuum/);
  assert.match(experience, /is-active/);
  assert.match(experience, /whileInView=\{motionOn \? \{ opacity: 1, y: 0, scale: 1 \} : undefined\}/);
  assert.match(experience, /current signal/);
  assert.match(experience, /Focus \$\{linkedProject.name\} through \$\{label\}/);
  assert.match(experience, /POS_APBDS/);
  assert.match(experience, /labQ-Android/);
  assert.match(experience, /className="mobile-nav"/);
  assert.match(experience, /document\.documentElement\.dataset\.cursor/);
  assert.match(experience, /MotionConfig/);
  assert.match(experience, /reducedMotionActive = motionReady/);
  assert.match(layout, /alternates: \{ canonical: "\/" \}/);
  assert.match(layout, /url: "\/"/);
  assert.match(robots, /sitemap\.xml/);
  assert.match(sitemap, /changeFrequency: "monthly"/);
  assert.match(canvas, /WebGLRenderer/);
  assert.match(canvas, /system\.rotation\.x/);
  assert.match(canvas, /dataset\.pitch/);
  assert.match(canvas, /orbitPhases/);
  assert.match(canvas, /planetSurfaceTexture/);
  assert.match(canvas, /TorusGeometry/);
  assert.match(canvas, /createPlanetMaps/);
  assert.match(canvas, /createProjectSculpture/);
  assert.match(canvas, /projectShellTexture/);
  assert.match(canvas, /transparent: true, opacity: \.12, depthWrite: false/);
  assert.match(canvas, /ACESFilmicToneMapping/);
  assert.match(canvas, /projectOrbits/);
  assert.match(canvas, /sampleOrbit\(orbitRadius, phase/);
  assert.match(canvas, /focusAnchor/);
  assert.doesNotMatch(canvas, /LineSegments|networkPairs/);
  assert.doesNotMatch(canvas, /SphereGeometry\(\.87/);
  assert.match(backdrop, /projectWorlds/);
  assert.match(backdrop, /galaxyDust/);
  assert.doesNotMatch(backdrop, /THREE\.Sprite/);
  assert.match(backdrop, /sectorSystem/);
  assert.match(backdrop, /sectorNodes/);
  assert.match(backdrop, /orbitRadius: 1\.45/);
  assert.match(backdrop, /solarOrbits/);
  assert.match(backdrop, /createStellarCore/);
  assert.match(backdrop, /THREE\.PointLight/);
  assert.match(backdrop, /createDeepSpace/);
  assert.match(backdrop, /gravityVisitors/);
  assert.doesNotMatch(`${styles}${experience}`, /cosmic-nebula\.png/);
  assert.doesNotMatch(backdrop, /constellationPairs/);
  assert.match(backdrop, /const owner = orbitPlanets\[index\]\.pivot\.position/);
  assert.match(backdrop, /createBlackHole/);
  assert.match(backdrop, /new THREE\.ShaderMaterial/);
  assert.match(backdrop, /smoothstep\(contactProgress\.get\(\), 0, \.65\)/);
  assert.match(experience, /ref=\{contactRef\} className="contact-section"/);
  assert.match(backdrop, /advanceGravityAge/);
  assert.match(canvas, /universeAngle \+= dt \* \.025/);
  assert.match(backdrop, /unsubscribeChapter\(\)/);
  assert.match(styles, /\.black-hole-fallback/);
  assert.doesNotMatch(experience, /className="sector-navigation"/);
  assert.match(experience, /universe-return/);
  assert.match(experience, /useState<"universe" \| "orbit">\("universe"\)/);
  assert.match(experience, /SatelliteReadout/);
  assert.match(experience, /anchor: `academic-/);
  assert.match(experience, /anchor: `client-/);
  assert.match(canvas, /satelliteCatalog/);
  assert.match(canvas, /createGalaxySystem/);
  assert.match(canvas, /galaxy-label/);
  assert.match(canvas, /viewBlend/);
  assert.match(read("components/gravity-field.ts"), /travel \* \(\.75 \+ travel \* \.25\) \* turn/);
  assert.match(backdrop, /gravityMaterial/);
  assert.match(canvas, /satelliteTexture/);
  assert.match(canvas, /renderer\.forceContextLoss/);
  assert.match(styles, /max-height: calc\(100% - 118px\); overflow-y: auto; pointer-events: auto/);
  assert.match(backdrop, /planetSystem\.rotation\.y/);
  assert.match(backdrop, /SphereGeometry/);
  assert.match(canvas, /TechOrbitItem/);
  assert.match(canvas, /projectIds: readonly OrbitId\[\]/);
  assert.match(experience, /stack: \["PHP", "MySQL"\]/);
  assert.match(experience, /stack: \["C#", "WinForms"\]/);
  assert.match(experience, /stack: \["Java", "Android", "Laravel", "PostgreSQL"\]/);
  assert.match(experience, /yventures: \["n8n"\]/);
  assert.match(experience, /soreva: \["Node.js", "Next.js", "React", "TypeScript"\]/);
  assert.match(backdrop, /createSpacecraft/);
  assert.match(read("components/gravity-field.ts"), /horizonFade/);
  assert.match(canvas, /linkedProjectIndexes/);
  assert.match(canvas, /selectedProjectIndex/);
  assert.doesNotMatch(canvas, /safeOrbitX/);
  assert.match(canvas, /linkedTechCount/);
  assert.match(canvas, /planet\.orbitBlend/);
  assert.match(canvas, /techOrbitLanes/);
  assert.match(canvas, /anchorRadius/);
  assert.match(canvas, /techPlanetSurfaceTexture/);
  assert.match(canvas, /cdn\.simpleicons\.org/);
  assert.match(canvas, /paintLogo/);
  assert.match(canvas, /TorusGeometry\(radius \* 1\.42/);
  assert.match(canvas, /radiusPath = belongsToProject/);
  assert.match(canvas, /sampleTechOrbit\(radiusPath, lane, phase, orbitTarget\)/);
  assert.match(canvas, /frame\.attach\(group\)/);
  assert.match(canvas, /techOrbitFrames/);
  assert.doesNotMatch(canvas, /techRailCap/);
  assert.match(backdrop, /planetSurface = "opaque-terrain"/);
  assert.match(read("components/project-sculptures.ts"), /ExtrudeGeometry/);
  assert.match(styles, /prefers-reduced-motion/);
  assert.match(styles, /html\[data-motion="off"\]/);
  assert.match(styles, /touch-action: pan-y/);
  assert.match(styles, /loader-orbit-one/);
  assert.match(styles, /loader-scan/);
  assert.match(styles, /hero-transition-card/);
  assert.match(styles, /chain-float/);
  assert.match(styles, /\.work-section \{/);
  assert.match(styles, /background: radial-gradient\(ellipse at 12% 15%/);
  assert.match(styles, /scroll-padding-top: 84px/);
  assert.match(styles, /html\[data-cursor="quiet"\] \.cursor-guide/);
  assert.match(styles, /object-fit: contain/);
  assert.match(styles, /dossier-art-preview/);
  assert.match(styles, /dossier-private/);
  assert.match(styles, /\.signal-progress/);
  assert.match(styles, /data-visible="true"/);
  assert.match(styles, /\.maker-tech\.is-linked/);
  assert.match(styles, /\.maker-orbit-inspector/);
  assert.match(styles, /html\.lenis/);
  assert.match(smoothScroll, /new Lenis/);
  assert.match(smoothScroll, /gsap\.ticker/);
  assert.match(smoothScroll, /lenis\.raf/);
  assert.match(styles, /\.maker-core-portrait/);
  assert.match(styles, /@keyframes maker-portrait-scan/);
  assert.match(styles, /\.star-field--far/);
  assert.match(styles, /\.project-showcase \{[^}]*pointer-events: none/);
  assert.match(styles, /\.project-showcase button, \.project-showcase a \{ pointer-events: auto; \}/);
  assert.match(styles, /\.certificate-feature-switcher button \{ width: 44px; height: 44px; \}/);
  assert.match(styles, /\.client-signal-rail/);
  assert.match(styles, /@keyframes section-atmosphere/);
  assert.match(styles, /\.client-evidence-map/);
  assert.match(styles, /@keyframes evidence-map-scan/);
  assert.match(styles, /\.field-continuum/);
  assert.match(styles, /\.worldline-backdrop \{ position: fixed/);
  assert.match(styles, /@keyframes continuum-orbit-breathe/);
  assert.doesNotMatch(styles, /\.method-scene/);
  assert.match(styles, /\.project-signature/);
  assert.match(styles, /@keyframes signature-pulse/);
  assert.match(styles, /\.work-scroll-track/);
  assert.match(styles, /@media \(min-width: 641px\) and \(max-width: 900px\)/);
  assert.match(styles, /@media \(max-width: 420px\)/);
  assert.match(styles, /orientation: landscape/);
  assert.equal(existsSync(new URL("public/assets/background/cosmic-nebula.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/gemini-certified-educator.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/google-student-ambassador.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/source/gemini-certified-educator.pdf", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/gdg-spec-driven-development-antigravity-cli.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/source/gdg-code-quality-security-antigravity-cli.pdf", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/google-skills-arcade-voyage.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/projects/catmoji-hero.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/projects/nalira-ambient.svg", root)), true);
  assert.equal(existsSync(new URL("public/assets/projects/polara-og.png", root)), true);
  assert.equal(existsSync(new URL("app/icon.svg", root)), true);
});
