import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const root = new URL("..", import.meta.url);
const read = (path) => readFileSync(new URL(path, root), "utf8");

test("portfolio surface keeps its core experience contracts", () => {
  const experience = read("components/portfolio-experience.tsx");
  const canvas = read("components/cosmic-canvas.tsx");
  const backdrop = read("components/worldline-backdrop.tsx");
  const styles = read("app/globals.css");
  const layout = read("app/layout.tsx");
  const smoothScroll = read("components/smooth-scroll.tsx");
  const robots = read("app/robots.ts");
  const sitemap = read("app/sitemap.ts");

  assert.match(experience, /I build things I actually see\./);
  assert.match(experience, /Aku membangun hal yang benar-benar kulihat\./);
  assert.match(experience, /certificate shelf/);
  assert.match(experience, /certificate-shelf/);
  assert.match(experience, /certificate-modal/);
  assert.match(experience, /AnimatePresence/);
  assert.match(experience, /gemini-certified-educator\.png/);
  assert.match(experience, /google-student-ambassador\.png/);
  assert.match(experience, /The Henry method/);
  assert.match(experience, /Technology stack orbit/);
  assert.match(experience, /maker-orbit/);
  assert.match(experience, /case-facts/);
  assert.match(experience, /academic-runway/);
  assert.match(experience, /academic-card-signal/);
  assert.match(experience, /academic-card-stack/);
  assert.match(experience, /CarFront/);
  assert.match(experience, /FlaskConical/);
  assert.match(experience, /ShoppingCart/);
  assert.match(experience, /AI-Gesture-Cat/);
  assert.match(experience, /catmoji-hero\.png/);
  assert.match(experience, /polara-og\.png/);
  assert.match(experience, /\["PHP", "php"/);
  assert.match(experience, /tech-icon-fallback/);
  assert.match(experience, /loader-mark/);
  assert.match(experience, /className="loader-status"/);
  assert.doesNotMatch(experience, /loader-system/);
  assert.doesNotMatch(experience, /loader-telemetry/);
  assert.match(experience, /hero-transition/);
  assert.match(experience, /field-continuum-node/);
  assert.match(experience, /field-continuum-route/);
  assert.match(experience, /worldlineProgress/);
  assert.match(experience, /WorldlineStage/);
  assert.match(experience, /WorldlineBackdrop/);
  assert.doesNotMatch(experience, /signal-constellation/);
  assert.doesNotMatch(experience, /world-chain/);
  assert.match(experience, /project-showcase-index/);
  assert.match(experience, /dossier-art-evidence/);
  assert.match(experience, /access: Record<Language, string>/);
  assert.doesNotMatch(experience, /className="chapter-rail"/);
  assert.match(experience, /id="method"/);
  assert.match(experience, /signal-progress/);
  assert.doesNotMatch(experience, /PhaseBridge/);
  assert.match(experience, /--node-color/);
  assert.match(experience, /maker-orbit-inspector/);
  assert.match(experience, /SmoothScroll/);
  assert.match(experience, /data-lenis-prevent/);
  assert.match(experience, /maker-core-portrait/);
  assert.match(experience, /data-active-world=\{activeProject.id\}/);
  assert.match(experience, /client-signal-rail/);
  assert.match(experience, /client-owner-stamp/);
  assert.match(experience, /client-evidence-map/);
  assert.match(experience, /NO PRIVATE DATA/);
  assert.doesNotMatch(experience, /method-scene/);
  assert.match(experience, /offset: \["start 85%", "center center"\]/);
  assert.match(experience, /activeMethodStep = motionOn \? methodStep : 2/);
  assert.match(experience, /aria-current=\{index === activeMethodStep \? "step" : undefined\}/);
  assert.match(experience, /ProjectSignature/);
  assert.match(experience, /project signature/);
  assert.match(experience, /work-scroll-track/);
  assert.match(experience, /workProgress/);
  assert.match(experience, /stackStageRotate/);
  assert.match(experience, /field-continuum/);
  assert.match(experience, /is-active/);
  assert.match(experience, /whileInView=\{motionOn \? \{ opacity: 1, y: 0, scale: 1 \} : undefined\}/);
  assert.match(experience, /filter: "blur\(8px\)"/);
  assert.match(experience, /rotateY: -10/);
  assert.match(experience, /className="dossier-copy"/);
  assert.match(experience, /current signal/);
  assert.match(experience, /Focus \$\{linkedProject.name\} through \$\{label\}/);
  assert.match(experience, /POS_APBDS/);
  assert.match(experience, /labQ-Android/);
  assert.match(experience, /className="mobile-nav"/);
  assert.match(experience, /document\.documentElement\.dataset\.cursor/);
  assert.match(experience, /MotionConfig/);
  assert.match(experience, /reducedMotionActive = motionReady/);
  assert.match(layout, /alternates: \{ canonical: "\/" \}/);
  assert.match(layout, /url: "\/"/);
  assert.match(robots, /sitemap\.xml/);
  assert.match(sitemap, /changeFrequency: "monthly"/);
  assert.match(canvas, /WebGLRenderer/);
  assert.match(canvas, /system\.rotation\.x/);
  assert.match(canvas, /dataset\.pitch/);
  assert.match(canvas, /orbitPhases/);
  assert.match(canvas, /planetSurfaceTexture/);
  assert.match(canvas, /TorusGeometry/);
  assert.match(canvas, /createProjectSculpture/);
  assert.match(canvas, /networkPairs/);
  assert.match(canvas, /A spanning path keeps every world connected/);
  assert.match(canvas, /\[\[0, 1\], \[1, 2\], \[2, 4\], \[4, 3\]\]/);
  assert.match(canvas, /LineSegments/);
  assert.doesNotMatch(canvas, /SphereGeometry\(\.87/);
  assert.match(backdrop, /projectWorlds/);
  assert.match(backdrop, /galaxyDust/);
  assert.match(backdrop, /galaxyCore/);
  assert.match(backdrop, /sectorSystem/);
  assert.match(backdrop, /sectorNodes/);
  assert.match(backdrop, /orbitRadius: 3\.6/);
  assert.match(backdrop, /constellationLinks/);
  assert.match(backdrop, /constellationPairs = \[\[0, 1\], \[1, 2\], \[2, 4\], \[4, 3\]\]/);
  assert.match(backdrop, /const owner = orbitPlanets\[index\]\.pivot\.position/);
  assert.match(backdrop, /createBlackHole/);
  assert.match(backdrop, /new THREE\.ShaderMaterial/);
  assert.match(backdrop, /smoothstep\(pageProgress\.get\(\), \.8, \.98\)/);
  assert.match(backdrop, /unsubscribeChapter\(\)/);
  assert.match(styles, /\.black-hole-fallback/);
  assert.match(experience, /sector-navigation/);
  assert.match(experience, /SatelliteReadout/);
  assert.match(experience, /anchor: `academic-/);
  assert.match(experience, /anchor: `client-/);
  assert.match(canvas, /satelliteWorlds/);
  assert.match(canvas, /satelliteTexture/);
  assert.match(canvas, /renderer\.forceContextLoss/);
  assert.match(styles, /max-height: calc\(100% - 118px\); overflow-y: auto; pointer-events: auto/);
  assert.match(backdrop, /planetSystem\.rotation\.y/);
  assert.match(backdrop, /SphereGeometry/);
  assert.match(canvas, /TechOrbitItem/);
  assert.match(canvas, /projectIds: readonly ProjectId\[\]/);
  assert.match(canvas, /linkedProjectIndexes/);
  assert.match(canvas, /selectedProjectIndex/);
  assert.match(canvas, /safeOrbitX/);
  assert.match(canvas, /linkedTechCount/);
  assert.match(canvas, /THREE\.MathUtils\.damp\(group\.position/);
  assert.match(canvas, /techOrbitLanes/);
  assert.match(canvas, /anchorRadius/);
  assert.match(canvas, /techPlanetSurfaceTexture/);
  assert.match(canvas, /cdn\.simpleicons\.org/);
  assert.match(canvas, /paintLogo/);
  assert.match(canvas, /TorusGeometry\(radius \* 1\.42/);
  assert.match(canvas, /radiusPath = belongsToProject/);
  assert.match(canvas, /targetY = anchor\.y \+ Math\.sin\(phase\) \* radiusPath \* \(\.7/);
  assert.match(canvas, /techRailCap = !portrait/);
  assert.match(canvas, /techSystem\.rotation\.y/);
  assert.match(read("components/project-sculptures.ts"), /ExtrudeGeometry/);
  assert.match(styles, /prefers-reduced-motion/);
  assert.match(styles, /html\[data-motion="off"\]/);
  assert.match(styles, /touch-action: pan-y/);
  assert.match(styles, /loader-orbit-one/);
  assert.match(styles, /loader-scan/);
  assert.match(styles, /hero-transition-card/);
  assert.match(styles, /chain-float/);
  assert.match(styles, /\.work-section \{/);
  assert.match(styles, /background: radial-gradient\(ellipse at 12% 15%/);
  assert.match(styles, /scroll-padding-top: 84px/);
  assert.match(styles, /html\[data-cursor="quiet"\] \.cursor-guide/);
  assert.match(styles, /object-fit: contain/);
  assert.match(styles, /dossier-art-preview/);
  assert.match(styles, /dossier-private/);
  assert.match(styles, /\.signal-progress/);
  assert.match(styles, /data-visible="true"/);
  assert.match(styles, /\.maker-tech\.is-linked/);
  assert.match(styles, /\.maker-orbit-inspector/);
  assert.match(styles, /html\.lenis/);
  assert.match(smoothScroll, /new Lenis/);
  assert.match(smoothScroll, /gsap\.ticker/);
  assert.match(smoothScroll, /lenis\.raf/);
  assert.match(styles, /\.maker-core-portrait/);
  assert.match(styles, /@keyframes maker-portrait-scan/);
  assert.match(styles, /\.star-field--far/);
  assert.match(styles, /\.project-showcase \{[^}]*pointer-events: none/);
  assert.match(styles, /\.project-showcase button, \.project-showcase a \{ pointer-events: auto; \}/);
  assert.match(styles, /\.certificate-feature-switcher button \{ width: 44px; height: 44px; \}/);
  assert.match(styles, /\.client-signal-rail/);
  assert.match(styles, /@keyframes section-atmosphere/);
  assert.match(styles, /\.client-evidence-map/);
  assert.match(styles, /@keyframes evidence-map-scan/);
  assert.match(styles, /\.field-continuum/);
  assert.match(styles, /\.worldline-backdrop \{ position: fixed/);
  assert.match(styles, /@keyframes continuum-orbit-breathe/);
  assert.doesNotMatch(styles, /\.method-scene/);
  assert.match(styles, /\.project-signature/);
  assert.match(styles, /@keyframes signature-pulse/);
  assert.match(styles, /\.work-scroll-track/);
  assert.match(styles, /@media \(min-width: 641px\) and \(max-width: 900px\)/);
  assert.match(styles, /@media \(max-width: 420px\)/);
  assert.match(styles, /orientation: landscape/);
  assert.equal(existsSync(new URL("public/assets/background/cosmic-nebula.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/gemini-certified-educator.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/google-student-ambassador.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/source/gemini-certified-educator.pdf", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/gdg-spec-driven-development-antigravity-cli.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/source/gdg-code-quality-security-antigravity-cli.pdf", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/google-skills-arcade-voyage.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/projects/catmoji-hero.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/projects/nalira-ambient.svg", root)), true);
  assert.equal(existsSync(new URL("public/assets/projects/polara-og.png", root)), true);
  assert.equal(existsSync(new URL("app/icon.svg", root)), true);
});
