import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const root = new URL("..", import.meta.url);
const read = (path) => readFileSync(new URL(path, root), "utf8");

test("portfolio surface keeps its core experience contracts", () => {
  const experience = read("components/portfolio-experience.tsx");
  const canvas = read("components/cosmic-canvas.tsx");
  const styles = read("app/globals.css");

  assert.match(experience, /I build things I actually see\./);
  assert.match(experience, /Aku membangun hal yang benar-benar kulihat\./);
  assert.match(experience, /certificate shelf/);
  assert.match(experience, /certificate-shelf/);
  assert.match(experience, /certificate-modal/);
  assert.match(experience, /AnimatePresence/);
  assert.match(experience, /gemini-certified-educator\.png/);
  assert.match(experience, /google-student-ambassador\.png/);
  assert.match(experience, /The Henry method/);
  assert.match(experience, /Technology stack orbit/);
  assert.match(experience, /maker-orbit/);
  assert.match(experience, /case-facts/);
  assert.match(experience, /AI-Gesture-Cat/);
  assert.match(experience, /catmoji-hero\.png/);
  assert.match(experience, /polara-og\.png/);
  assert.match(experience, /\["PHP", "php"/);
  assert.match(experience, /tech-icon-fallback/);
  assert.match(experience, /loader-system/);
  assert.match(experience, /loader-telemetry/);
  assert.match(experience, /hero-transition/);
  assert.match(experience, /world-chain/);
  assert.match(experience, /project-showcase-index/);
  assert.match(experience, /dossier-art-evidence/);
  assert.doesNotMatch(experience, /className="chapter-rail"/);
  assert.match(experience, /id="method"/);
  assert.match(experience, /signal-progress/);
  assert.doesNotMatch(experience, /PhaseBridge/);
  assert.match(experience, /--node-color/);
  assert.match(experience, /className="mobile-nav"/);
  assert.match(experience, /document\.documentElement\.dataset\.cursor/);
  assert.match(experience, /MotionConfig/);
  assert.match(canvas, /WebGLRenderer/);
  assert.match(canvas, /orbitPhases/);
  assert.match(canvas, /planetSurfaceTexture/);
  assert.match(canvas, /TorusGeometry/);
  assert.match(canvas, /createProjectSculpture/);
  assert.match(canvas, /networkPairs/);
  assert.match(canvas, /LineSegments/);
  assert.doesNotMatch(canvas, /SphereGeometry\(\.87/);
  assert.match(read("components/project-sculptures.ts"), /ExtrudeGeometry/);
  assert.match(styles, /prefers-reduced-motion/);
  assert.match(styles, /html\[data-motion="off"\]/);
  assert.match(styles, /touch-action: pan-y/);
  assert.match(styles, /loader-orbit-one/);
  assert.match(styles, /loader-scan/);
  assert.match(styles, /hero-transition-card/);
  assert.match(styles, /chain-float/);
  assert.match(styles, /\.work-section \{/);
  assert.match(styles, /background: radial-gradient\(ellipse at 12% 15%/);
  assert.match(styles, /scroll-padding-top: 84px/);
  assert.match(styles, /html\[data-cursor="quiet"\] \.cursor-guide/);
  assert.match(styles, /object-fit: contain/);
  assert.match(styles, /dossier-art-preview/);
  assert.match(styles, /dossier-private/);
  assert.match(styles, /\.signal-progress/);
  assert.match(styles, /data-visible="true"/);
  assert.equal(existsSync(new URL("public/assets/background/cosmic-nebula.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/gemini-certified-educator.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/google-student-ambassador.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/source/gemini-certified-educator.pdf", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/gdg-spec-driven-development-antigravity-cli.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/source/gdg-code-quality-security-antigravity-cli.pdf", root)), true);
  assert.equal(existsSync(new URL("public/assets/certificates/previews/google-skills-arcade-voyage.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/projects/catmoji-hero.png", root)), true);
  assert.equal(existsSync(new URL("public/assets/projects/polara-og.png", root)), true);
  assert.equal(existsSync(new URL("app/icon.svg", root)), true);
});
