import assert from "node:assert/strict";
import { mkdirSync } from "node:fs";
import { chromium, expect } from "@playwright/test";

const base = (process.env.PORTFOLIO_URL ?? "http://localhost:3002").replace(/\/$/, "");
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH ?? "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" });
const viewports = [{ width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }, { width: 360, height: 740 }, { width: 844, height: 390 }];
mkdirSync("test-results/libraries", { recursive: true });
async function fits(page) {
  await expect(page.locator("html")).toHaveAttribute("data-preferences-ready", "true", { timeout: 20000 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "No horizontal overflow");
  assert.equal(await page.locator("canvas").count(), 1, "Reading routes mount only the shared quiet sky, not the project map");
  await expect(page.locator(".reading-sky")).toHaveAttribute("data-ready", "true");
  assert.ok(Number(await page.locator(".reading-sky").getAttribute("data-draw-calls")) <= 2);
  assert.ok(await page.locator(".reading-sky canvas").evaluate(canvas => {
    const gl = canvas.getContext("webgl2"), pixels = new Uint8Array(canvas.width * canvas.height * 4);
    gl.readPixels(0, 0, canvas.width, canvas.height, gl.RGBA, gl.UNSIGNED_BYTE, pixels);
    let lit = 0;
    for (let i = 0; i < pixels.length; i += 4) if (pixels[i] + pixels[i + 1] + pixels[i + 2] > 30) lit++;
    return lit > canvas.width * canvas.height * .02;
  }), "Reading sky must paint real nebula pixels");
}
try {
  for (const viewport of process.argv.includes("--integration") ? [] : viewports) {
    const page = await browser.newPage({ viewport });
    const errors = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto(`${base}/projects`, { waitUntil: "domcontentloaded" });
    await expect(page.locator(".project-record")).toHaveCount(10);
    await fits(page);
    await page.screenshot({ path: `test-results/libraries/${viewport.width}-projects.png`, animations: "disabled" });
    await page.getByRole("button", { name: "University", exact: true }).click();
    await expect(page.locator(".project-record")).toHaveCount(3);
    await page.getByRole("searchbox", { name: "Search projects" }).fill("Laravel");
    await expect(page.locator(".project-record")).toHaveCount(1);
    await page.getByRole("link", { name: "LabQ", exact: true }).click();
    await expect(page.locator("h1")).toHaveText("LabQ");
    await fits(page);
    await expect(page.locator(".detail-continuation")).toHaveCount(0);
    await expect(page.getByRole("link", { name: "Read source", exact: true })).toHaveAttribute("href", "https://github.com/nugrahahenry/labQ-Android");
    await page.getByRole("link", { name: "All projects", exact: true }).click();
    await expect(page.locator(".project-record")).toHaveCount(1);
    await expect(page.getByRole("searchbox")).toHaveValue("Laravel");
    await page.reload({ waitUntil: "domcontentloaded" });
    await expect(page.locator(".project-record")).toHaveCount(1);
    await page.goto(`${base}/projects/pos-z-shoes?category=university`);
    await expect(page.locator(".detail-continuation a")).toHaveCount(2);
    await page.locator(".detail-continuation").scrollIntoViewIfNeeded();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.screenshot({ path: `test-results/libraries/${viewport.width}-continuation.png` });
    await page.locator(".detail-neighbor--next").click();
    await expect(page.locator("h1")).toHaveText("LabQ");
    await expect(page).toHaveURL(/category=university/);
    await page.getByRole("link", { name: "All projects", exact: true }).click();
    await expect(page.locator(".project-record")).toHaveCount(3);
    await page.goto(`${base}/credentials`);
    await expect(page.locator(".credential-record")).toHaveCount(26);
    await fits(page);
    await expect(page.locator(".credential-record").first()).toContainText("Google Student Ambassador");
    if (viewport.width <= 1000) {
      const search = await page.locator(".credential-filters .library-search").boundingBox();
      const type = await page.getByRole("combobox", { name: "Type", exact: true }).boundingBox();
      const issuer = await page.getByRole("combobox", { name: "Issuer", exact: true }).boundingBox();
      assert.ok(Math.abs(type.y - issuer.y) < 1 && search.y + search.height < type.y, "Tablet/phone filters align below the full-width search");
    }
    await page.screenshot({ path: `test-results/libraries/${viewport.width}-credentials.png`, animations: "disabled" });
    const trigger = page.getByRole("button", { name: "Open Class of 2026 Graduation", exact: true });
    await trigger.click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    await expect(dialog.locator(".credential-dialog-stage")).toHaveAttribute("data-image-state", "ready");
    assert.ok(await dialog.locator("[data-credential-original]").evaluate(image => image.complete && image.naturalWidth > 0));
    const bounds = await dialog.boundingBox();
    assert.ok(bounds.x >= 0 && bounds.y >= 0 && bounds.x + bounds.width <= viewport.width && bounds.y + bounds.height <= viewport.height);
    await page.screenshot({ path: `test-results/libraries/${viewport.width}-viewer.png` });
    const historyLength = await page.evaluate(() => history.length);
    await dialog.evaluate(node => { node.dataset.testInstance = "original-dialog"; });
    await expect(dialog.getByRole("button", { name: "Previous certificate", exact: true })).toBeDisabled();
    await dialog.getByRole("button", { name: "Next certificate", exact: true }).click();
    await expect(dialog.locator("h2")).toHaveText("Gemini Certified Educator");
    await expect(page).toHaveURL(/record=gemini-certified/);
    await expect(dialog.locator(".credential-dialog-count")).toHaveText("02 / 26");
    await page.keyboard.press("ArrowLeft");
    await expect(dialog.locator("h2")).toHaveText("Class of 2026 Graduation");
    await page.keyboard.press("ArrowRight");
    await expect(dialog.locator("h2")).toHaveText("Gemini Certified Educator");
    await expect(dialog).toHaveAttribute("data-test-instance", "original-dialog");
    assert.equal(await page.evaluate(() => history.length), historyLength, "Gallery changes replace URL state without flooding history");
    await expect(dialog.locator(".credential-dialog-stage")).toHaveAttribute("data-image-state", "ready");
    await dialog.getByRole("button", { name: "Zoom certificate", exact: true }).click();
    await expect(dialog.getByRole("region", { name: "Certificate image" })).toBeFocused();
    assert.ok(await dialog.locator(".credential-dialog-image").evaluate(el => el.scrollWidth > el.clientWidth), "Zoomed image can be panned");
    await page.keyboard.press("ArrowRight");
    await expect(dialog.locator("h2")).toHaveText("Gemini Certified Educator");
    await dialog.getByRole("button", { name: "Next certificate", exact: true }).click();
    await expect(dialog.locator("h2")).toHaveText("Gemini Certified Student");
    await expect(dialog.locator(".credential-dialog-stage")).toHaveAttribute("data-image-state", "ready");
    await expect(dialog.locator(".credential-dialog-image")).not.toHaveClass(/is-zoomed/);
    await dialog.getByRole("button", { name: "Zoom certificate", exact: true }).click();
    await dialog.getByRole("button", { name: "Fit certificate", exact: true }).click();
    for (let i = 0; i < 7; i++) { await page.keyboard.press("Tab"); assert.ok(await dialog.evaluate(el => el.contains(document.activeElement))); }
    await page.keyboard.press("Escape");
    await expect(dialog).toHaveCount(0);
    await expect(trigger).toBeFocused();
    await page.getByRole("combobox", { name: "Type", exact: true }).selectOption("Competition");
    await expect(page.locator(".credential-record")).toHaveCount(2);
    await page.locator(".credential-record-preview").first().click();
    await expect(page.locator(".credential-dialog-count")).toHaveText("01 / 02");
    await page.getByRole("button", { name: "Next certificate", exact: true }).click();
    await expect(page.locator(".credential-dialog-count")).toHaveText("02 / 02");
    await expect(page.getByRole("button", { name: "Next certificate", exact: true })).toBeDisabled();
    await expect(page.getByRole("button", { name: "Close certificate viewer", exact: true })).toBeFocused();
    await page.keyboard.press("Escape");
    await page.getByRole("searchbox").fill("zzzzzz");
    await expect(page.locator(".credential-record")).toHaveCount(0);
    await page.getByRole("button", { name: "Clear filters" }).first().click();
    await expect(page.locator(".credential-record")).toHaveCount(26);
    assert.deepEqual(errors, []);
    await page.close();
    console.log(`Libraries, query return/reload, viewer/focus, overflow passed at ${viewport.width}x${viewport.height}`);
  }
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  await page.goto(`${base}/projects`);
  await fits(page);
  await page.locator(".project-record").first().locator(".project-record-visual").click();
  await expect(page.locator("h1")).toHaveText("Catmoji");
  await page.goBack();
  await page.getByRole("link", { name: "Nalira", exact: true }).focus();
  await page.keyboard.press("Enter");
  await expect(page.locator("h1")).toHaveText("Nalira");
  await page.goto(`${base}/projects?lang=id&motion=off&category=client`);
  await expect(page.locator(".project-record")).toHaveCount(2);
  await expect(page.locator("html")).toHaveAttribute("lang", "id");
  await page.getByRole("link", { name: "Soreva Autonomous Content", exact: true }).click();
  await expect(page).toHaveURL(/lang=id/);
  await expect(page).toHaveURL(/motion=off/);
  await expect(page.locator(".detail-facts")).toContainText("Vieri");
  await expect(page.locator(".detail-continuation a")).toHaveCount(1);
  await expect(page.locator(".detail-continuation a")).toHaveAttribute("href", /category=client.*lang=id.*motion=off/);
  await page.goBack();
  await expect(page.locator(".project-record")).toHaveCount(2);
  await page.locator(".desktop-nav").getByRole("link", { name: "Credentials" }).click();
  await expect(page.locator("h1")).toHaveText("Jejak belajar.");
  await expect(page.locator("html")).toHaveAttribute("data-motion", "off");
  await page.goto(`${base}/credentials?kind=Certification&record=gemini-certified`);
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.reload();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("combobox", { name: "Type", exact: true })).toHaveValue("Certification");
  await page.goto(`${base}/credentials?kind=Competition&record=gemini-certified`);
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.locator(".credential-dialog-navigation")).toHaveCount(0);
  await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("dialog").locator("h2")).toHaveText("Gemini Certified Student");
  await page.keyboard.press("Escape");
  await page.goto(`${base}/projects/rentalmobil-sg?from=universe`);
  await expect(page.locator(".detail-route")).toContainText("University / 01 of 03");
  await page.locator(".detail-neighbor--next").click();
  await expect(page).toHaveURL(/\/projects\/pos-z-shoes\?from=universe/);
  await expect(page.getByRole("link", { name: "Back to the universe", exact: true })).toHaveAttribute("href", /\/\?world=pos$/);
  await page.locator(".detail-neighbor--next").click();
  await expect(page.locator("h1")).toHaveText("LabQ");
  await expect(page.locator(".detail-neighbor--next")).toHaveCount(0);
  await page.screenshot({ path: "test-results/libraries/detail-continuation.png", fullPage: true });
  await page.goto(`${base}/projects/not-a-project`);
  await expect(page.locator("h1")).toHaveText("World not found.");
  await page.getByRole("link", { name: "Skip to content", exact: true }).focus();
  await page.keyboard.press("Enter");
  await expect(page.locator("#main-content")).toBeFocused();
  await page.goto(`${base}/credentials?kind=invalid&record=unknown`);
  await expect(page.locator(".credential-record")).toHaveCount(26);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.goto(`${base}/projects?lang=id&motion=off`);
  await expect(page.locator("html")).toHaveAttribute("data-preferences-ready", "true");
  await page.locator(".desktop-nav").getByRole("link", { name: "Kontak" }).click();
  await expect(page.locator("#contact h2")).toBeInViewport({ timeout: 20000 });
  await expect(page.locator(".reading-sky")).toHaveCount(0);
  await expect(page.locator("canvas")).toHaveCount(2);
  await page.goto(`${base}/?lang=id&motion=off#academic-3`);
  await expect(page.locator("h1")).toHaveText("LabQ");
  await expect(page).toHaveURL(/\/projects\/labq\?lang=id&motion=off/);
  await page.goto(`${base}/#client-work`);
  await page.waitForURL(/\/projects\?category=client/, { waitUntil: "domcontentloaded", timeout: 20000 });
  await fits(page);
  await expect(page.locator(".project-record")).toHaveCount(2);
  await expect(page).toHaveURL(/category=client/);
  for (const slug of ["catmoji", "nalira", "canox", "hengs", "polara", "rentalmobil-sg", "pos-z-shoes", "labq", "y-ventures", "soreva"]) {
    const response = await page.request.get(`${base}/projects/${slug}`);
    assert.equal(response.status(), 200, slug);
    assert.match(await response.text(), /rel="canonical"/);
  }
  assert.equal((await page.request.get(`${base}/projects/unknown`)).status(), 404);
  await page.close();
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await mobile.goto(`${base}/projects?motion=off`);
  await fits(mobile);
  await mobile.keyboard.press("Tab");
  await expect(mobile.getByRole("link", { name: "Skip to content", exact: true })).toBeFocused();
  await mobile.keyboard.press("Enter");
  await expect(mobile.locator("#main-content")).toBeFocused();
  const menu = mobile.locator(".mobile-nav");
  const summary = menu.locator("summary");
  await summary.click();
  await expect(menu).toHaveAttribute("open", "");
  await expect(menu.getByRole("link", { name: "Projects", exact: true })).toHaveAttribute("aria-current", "page");
  await mobile.locator("h1").click();
  await expect(menu).not.toHaveAttribute("open", "");
  await summary.click();
  await mobile.keyboard.press("Escape");
  await expect(summary).toBeFocused();
  await expect(menu).not.toHaveAttribute("open", "");
  await summary.click();
  await mobile.locator(".language-toggle").focus();
  await expect(menu).not.toHaveAttribute("open", "");
  await summary.click();
  await menu.getByRole("link", { name: "Credentials", exact: true }).click();
  await expect(mobile.locator("h1")).toHaveText("Credentials.");
  await expect(menu).not.toHaveAttribute("open", "");
  await summary.click();
  await expect(menu.getByRole("link", { name: "Credentials", exact: true })).toHaveAttribute("aria-current", "page");
  await mobile.screenshot({ path: "test-results/libraries/mobile-navigation.png" });
  await mobile.close();
  const reduced = await browser.newPage({ reducedMotion: "reduce" });
  await reduced.goto(`${base}/projects`);
  await fits(reduced);
  await expect(reduced.locator("html")).toHaveAttribute("data-motion", "off");
  await expect(reduced.locator(".motion-toggle")).toBeDisabled();
  const still = await reduced.locator(".reading-sky").getAttribute("data-time");
  await reduced.waitForTimeout(200);
  assert.equal(await reduced.locator(".reading-sky").getAttribute("data-time"), still);
  await reduced.close();
  const sky = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await sky.goto(`${base}/projects`);
  await fits(sky);
  const before = Number(await sky.locator(".reading-sky").getAttribute("data-time"));
  await expect.poll(async () => Number(await sky.locator(".reading-sky").getAttribute("data-time"))).toBeGreaterThan(before + .1);
  await sky.locator(".reading-sky canvas").evaluate(canvas => canvas.getContext("webgl2").getExtension("WEBGL_lose_context").loseContext());
  await expect(sky.locator(".reading-sky")).toHaveAttribute("data-fallback", "true");
  await expect(sky.getByRole("link", { name: "Catmoji", exact: true })).toBeVisible();
  await sky.getByRole("link", { name: "Catmoji", exact: true }).click();
  await expect(sky.locator("h1")).toHaveText("Catmoji");
  await sky.close();
  for (const language of ["en", "id"]) {
    const recovery = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const errors = [];
    recovery.on("pageerror", error => errors.push(error.message));
    let release;
    const pending = new Promise(resolve => { release = resolve; });
    await recovery.route("**/assets/certificates/previews/google-student-ambassador.png*", async route => {
      if (route.request().url().includes("retry=")) return route.continue();
      await pending;
      await route.abort("failed");
    });
    try {
      await recovery.goto(`${base}/credentials?lang=${language}&motion=off`);
      await fits(recovery);
      const isEn = language === "en";
      const trigger = recovery.getByRole("button", { name: `${isEn ? "Open" : "Buka"} Class of 2026 Graduation`, exact: true });
      await trigger.click();
      const dialog = recovery.getByRole("dialog");
      await expect(dialog.locator(".credential-dialog-stage")).toHaveAttribute("data-image-state", "loading");
      await expect(dialog.getByRole("button", { name: isEn ? "Zoom certificate" : "Perbesar sertifikat", exact: true })).toBeDisabled();
      await expect.poll(() => dialog.locator(".credential-dialog-preview").evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true);
      await recovery.screenshot({ path: `test-results/libraries/viewer-loading-${language}.png` });
      release();
      await expect(dialog.getByRole("alert")).toContainText(isEn ? "could not load" : "belum berhasil");
      await recovery.screenshot({ path: `test-results/libraries/viewer-error-${language}.png` });
      await dialog.getByRole("button", { name: isEn ? "Retry image" : "Coba muat lagi", exact: true }).click();
      await expect(dialog.getByRole("button", { name: isEn ? "Close certificate viewer" : "Tutup sertifikat", exact: true })).toBeFocused();
      await expect(dialog.locator(".credential-dialog-stage")).toHaveAttribute("data-image-state", "ready");
      await expect(dialog.locator(".credential-dialog-preview")).toHaveCount(0);
      const zoom = dialog.getByRole("button", { name: isEn ? "Zoom certificate" : "Perbesar sertifikat", exact: true });
      await zoom.click();
      await expect(dialog.getByRole("region")).toBeFocused();
      await expect(dialog.getByRole("button", { name: isEn ? "Fit certificate" : "Sesuaikan sertifikat", exact: true })).toHaveAttribute("aria-pressed", "true");
      await recovery.keyboard.press("Escape");
      await expect(trigger).toBeFocused();
      await recovery.getByRole("button", { name: `${isEn ? "Open" : "Buka"} Gemini Certified Educator`, exact: true }).click();
      await expect(recovery.locator(".credential-dialog-stage")).toHaveAttribute("data-image-state", "ready");
      await expect(recovery.locator(".credential-dialog-image")).not.toHaveClass(/is-zoomed/);
      assert.deepEqual(errors, []);
      console.log(`Credential slow-load, failure, retry, localized zoom, focus, and record reset passed: ${language}`);
    } finally { release(); await recovery.close(); }
  }
  console.log("Language/motion propagation, native Back, direct viewer URLs, unknown values, 404, and reduced motion passed.");
  console.log("Cross-route Contact and all ten detail HTTP/canonical routes passed.");
} finally { await browser.close(); }
