export const credentialRecords = [
  { title: "Class of 2026 Graduation", issuer: "Google Student Ambassador", kind: "Community", date: "Class of 2026", image: "/assets/certificates/previews/google-student-ambassador.png", source: "/assets/certificates/source/google-student-ambassador.pdf", alt: "Google Student Ambassador Class of 2026 graduation certificate for Henry Nugraha" },
  { title: "Gemini Certified Educator", issuer: "Google", kind: "Certification", date: "18 Apr 2026", image: "/assets/certificates/previews/gemini-certified-educator.png", source: "/assets/certificates/source/gemini-certified-educator.pdf", alt: "Gemini Certified Educator certificate for Henry Nugraha" },
  { title: "Gemini Certified Student", issuer: "Google", kind: "Certification", date: "08 Apr 2026", image: "/assets/certificates/previews/gemini-certified.png", source: "/assets/certificates/source/gemini-certified.pdf", alt: "Gemini Certified Student certificate for Henry Nugraha" },
  { title: "TechSprint Web Development", issuer: "Codelab Indonesia", kind: "Competition", date: "Date not shown", image: "/assets/certificates/previews/codelab-techsprint-web-development.png", source: "/assets/certificates/source/codelab-techsprint-web-development.pdf", alt: "TechSprint Innovation Cup Web Development certificate for Henry Nugraha" },
  { title: "Belajar Prinsip Pemrograman SOLID", issuer: "Dicoding Academy", kind: "Course", date: "30 Apr 2026", image: "/assets/certificates/previews/dicoding-oop.png", source: "/assets/certificates/source/dicoding-oop.pdf", alt: "Dicoding certificate for learning SOLID programming principles" },
  { title: "Top 10 Finalist RBCA", issuer: "IMPACT / Retail Business Case Analysis", kind: "Competition", date: "Date not shown", image: "/assets/certificates/previews/top-ten-rbca.jpeg", alt: "Top 10 Finalist Retail Business Case Analysis certificate for Henry Nugraha" },
  { title: "Google Workspace for Education Fundamentals", issuer: "Google for Education", kind: "Credential", date: "Date not shown", image: "/assets/certificates/previews/google-for-education.png", source: "/assets/certificates/source/google-for-education.pdf", alt: "Google Workspace for Education Fundamentals credential for Henry Nugraha" },
  { title: "Build Your First Agent with ADK", issuer: "Google Skills", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-skills-build-first-agent.png", alt: "Google Skills badge for Build Your First Agent with Agent Development Kit" },
  { title: "Spec-Driven Development with Antigravity CLI", issuer: "GDG Jakarta / GDG Cloud Jakarta", kind: "Workshop record", date: "22 Jul 2026", image: "/assets/certificates/previews/gdg-spec-driven-development-antigravity-cli.png", source: "/assets/certificates/source/gdg-spec-driven-development-antigravity-cli.pdf", alt: "GDG recognition of engagement for Spec-Driven Development with Antigravity CLI, issued to Henry Nugraha" },
  { title: "AI-Assisted Checks with Antigravity CLI and SDK", issuer: "GDG Jakarta / GDG Cloud Jakarta", kind: "Workshop record", date: "24 Jul 2026", image: "/assets/certificates/previews/gdg-code-quality-security-antigravity-cli.png", source: "/assets/certificates/source/gdg-code-quality-security-antigravity-cli.pdf", alt: "GDG recognition of engagement for AI-assisted code quality and security checks, issued to Henry Nugraha" },
  { title: "App Building with AppSheet", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-adventure-app-building-appsheet.png", alt: "Google Cloud skill badge for App Building with AppSheet" },
  { title: "Build Serverless Applications with Cloud Run Functions", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-adventure-build-serverless-applications.png", alt: "Google Cloud skill badge for building serverless applications with Cloud Run Functions" },
  { title: "Build a Data Mesh with Dataplex", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-data-mesh-knowledge-catalog.png", alt: "Google Cloud skill badge for building a data mesh with Dataplex" },
  { title: "Build a Data Warehouse with BigQuery", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-data-warehouse-bigquery.png", alt: "Google Cloud skill badge for building a data warehouse with BigQuery" },
  { title: "Mitigate Threats with Security Command Center", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-safe-space-security-command-center.png", alt: "Google Cloud skill badge for mitigating threats and vulnerabilities with Security Command Center" },
  { title: "Optimize Costs for Google Kubernetes Engine", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-safe-space-optimize-costs-kubernetes-engine.png", alt: "Google Cloud skill badge for optimizing costs for Google Kubernetes Engine" },
  { title: "Create Your First Gemini Enterprise Application", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-skills-create-gemini-enterprise-application.png", alt: "Google Cloud skill badge for creating a Gemini Enterprise application" },
  { title: "Deploy Multi-Agent Architectures", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-skills-deploy-multi-agent-architectures.png", alt: "Google Cloud skill badge for deploying multi-agent architectures" },
  { title: "Engineer AI Agents with ADK", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-skills-engineer-ai-agents-adk.png", alt: "Google Cloud skill badge for engineering AI agents with Agent Development Kit" },
  { title: "Gemini for Data Scientists and Analysts", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-skills-gemini-data-scientists-analysts.png", alt: "Google Cloud completion badge for Gemini for Data Scientists and Analysts" },
  { title: "Optimize Agent Behavior", issuer: "Google Cloud", kind: "Completion badge", date: "Date not shown", image: "/assets/certificates/previews/google-skills-optimize-agent-behavior.png", alt: "Google Cloud completion badge for optimizing agent behavior" },
  { title: "Google Skills Arcade: Base Camp", issuer: "Google Cloud", kind: "Completion badge", date: "Jul 2026", image: "/assets/certificates/previews/google-skills-arcade-base-camp.png", alt: "Google Skills Arcade Base Camp badge from July 2026" },
  { title: "Google Skills Arcade: Data Mesh Architect", issuer: "Google Cloud", kind: "Completion badge", date: "Jul 2026", image: "/assets/certificates/previews/google-skills-arcade-data-mesh-architect.png", alt: "Google Skills Arcade Data Mesh Architect badge from July 2026" },
  { title: "Google Skills Arcade: Low-Code Development", issuer: "Google Cloud", kind: "Completion badge", date: "Jul 2026", image: "/assets/certificates/previews/google-skills-arcade-low-code-development.png", alt: "Google Skills Arcade Low-Code Development badge from July 2026" },
  { title: "Google Skills Arcade: Safe Space", issuer: "Google Cloud", kind: "Completion badge", date: "Jul 2026", image: "/assets/certificates/previews/google-skills-arcade-safe-space.png", alt: "Google Skills Arcade Safe Space badge from July 2026" },
  { title: "Google Skills Arcade: Voyage", issuer: "Google Cloud", kind: "Completion badge", date: "Jul 2026", image: "/assets/certificates/previews/google-skills-arcade-voyage.png", alt: "Google Skills Arcade Voyage badge from July 2026" },
];

export const certificateFilters = ["All", "Certification", "Course", "Competition", "Community", "Credential", "Completion badge", "Workshop record"] as const;

export const certificates = credentialRecords.map((record, index) => ({ ...record, id: record.image.split("/").pop()!.replace(/\.[^.]+$/, ""), thumbnail: record.image.replace("/previews/", "/thumbnails/").replace(/\.[^.]+$/, ".webp"), featuredOrder: index < 5 ? index : null }));
export type Credential = (typeof certificates)[number];
